# Overview of database and generated results

## 1. Results
Visualize the Prediction results (-> result.pkl) which is generated in eval_utils:

In [1]:
import pickle
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from tabulate import tabulate

# Load the result.pkl file
result_file_path = 'output/models/kitti/VirConv-T/Subset_Eight_Hundred/eval/epoch_40/val/default/result.pkl'

with open(result_file_path, 'rb') as f:
    result = pickle.load(f)
    # print(result)


# Create a DataFrame from the result
data = []
for item in result:
    for i in range(len(item['name'])):
        data.append({
            'name': item['name'][i],
            'truncated': item['truncated'][i],
            'occluded': item['occluded'][i],
            'alpha': item['alpha'][i],
            'bbox': item['bbox'][i],
            'dimensions': item['dimensions'][i],
            'location': item['location'][i],
            'rotation_y': item['rotation_y'][i],
            'score': item['score'][i],
            'frame_id': item['frame_id']
        })

df = pd.DataFrame(data)

# Print the DataFrame as a table
print(tabulate(df, headers='keys', tablefmt='psql'))

+-----+--------+-------------+------------+------------+-----------------------------------------------+---------------------------------+---------------------------------------------+--------------+----------+------------+
|     | name   |   truncated |   occluded |      alpha | bbox                                          | dimensions                      | location                                    |   rotation_y |    score |   frame_id |
|-----+--------+-------------+------------+------------+-----------------------------------------------+---------------------------------+---------------------------------------------+--------------+----------+------------|
|   0 | Car    |           0 |          0 | -1.65576   | [624.324   174.33472 648.32007 195.22191]     | [3.9131808 1.4774268 1.6181307] | [ 2.08507    1.6017811 58.74869  ]          |  -1.62083    | 0.4      |     000064 |
|   1 | Car    |           0 |          0 | -1.60033   | [627.57605 174.2145  648.86346 195.1366 ]     | [3.7273335 1.4822391 1.6121968] | [ 2.2402904  1.5960692 58.659725 ]          |  -1.56272    | 0.4      |     000064 |
|   2 | Car    |           0 |          0 | -1.69368   | [622.7007  174.30061 648.66486 195.32654]     | [3.9293957 1.4881166 1.6361713] | [ 2.0318384  1.6097199 58.773407 ]          |  -1.65967    | 0.4      |     000064 |
|   3 | Car    |           0 |          0 | -1.58839   | [627.95886 174.14415 648.938   195.07806]     | [3.91697   1.4827908 1.6299639] | [ 2.2613811  1.5910695 58.750206 ]          |  -1.55048    | 0.4      |     000064 |
|   4 | Car    |           0 |          0 | -1.83544   | [730.77795 178.21309 882.0198  275.94125]     | [3.9740436 1.5294183 1.6688383] | [ 3.419326  1.644415 13.517583]             |  -1.59387    | 0.998248 |     000064 |
|   5 | Car    |           0 |          0 | -1.69548   | [658.7105  178.27182 712.99884 220.50328]     | [3.4274173 1.4442031 1.5747275] | [ 2.713557   1.6585485 26.852802 ]          |  -1.59653    | 0.985344 |     000064 |
|   6 | Car    |           0 |          0 | -1.79403   | [714.6448  175.91615 762.764   205.07178]     | [4.215334  1.4812493 1.6665173] | [ 6.895379   1.6566635 39.25626  ]          |  -1.62192    | 0.961781 |     000064 |
|   7 | Car    |           0 |          0 | -1.65205   | [625.1601  174.26915 649.17554 195.00575]     | [3.9931347 1.4656457 1.6279315] | [ 2.1543534  1.5846119 58.7794   ]          |  -1.61597    | 0.745226 |     000064 |
|   8 | Car    |           0 |          0 | -1.55847   | [580.95514 172.35141 604.0004  196.01471]     | [3.8176467 1.5427989 1.6411891] | [-1.302324   1.5067055 53.304684 ]          |  -1.58315    | 0.4      |     000260 |
|   9 | Car    |           0 |          0 | -4.5665    | [553.65424 169.61768 579.3154  190.85457]     | [4.0224447 1.655339  1.7132146] | [-3.8584163  1.3765514 64.16571  ]          |  -4.62661    | 0.4      |     000260 |
|  10 | Car    |           0 |          0 | -4.63554   | [553.8954 170.5543 576.2953 190.4057]         | [4.2899275 1.5401261 1.6733379] | [-3.9981258  1.3414205 64.40774  ]          |  -4.69757    | 0.4      |     000260 |
|  11 | Car    |           0 |          0 | -1.58484   | [580.8791  173.24252 603.7372  196.76917]     | [3.7891831 1.5273991 1.6240742] | [-1.3633801  1.5567768 53.19096  ]          |  -1.61073    | 0.4      |     000260 |
|  12 | Car    |           0 |          0 | -4.60498   | [553.68726 169.87173 577.8391  190.85902]     | [4.241343  1.6369789 1.7075578] | [-3.9342186  1.3795643 64.364914 ]          |  -4.66607    | 0.584439 |     000260 |
|  13 | Car    |           0 |          0 | -1.58867   | [580.6443  172.87178 603.99414 196.41348]     | [4.0025935 1.5336032 1.6485802] | [-1.3700144  1.5346687 53.406757 ]          |  -1.61456    | 0.570832 |     000260 |
|  14 | Car    |           0 |          0 | -1.78932   | [497.5512  173.80789 538.13275 200.39967]     | [3.735167  1.5088714 1.6283501] | [-5.5849843  1.5682657 43.12053  ]          |  -1.91773    | 0.4      |     000342 |
|  15 | Car    |           0 |          0 | -1.77999   | [498.58273 173.35057 538.1409  200.77888]     | [3.5729842 1.5593574 1.6288366] | [-5.5418625  1.5900285 43.047016 ]          |  -1.90765    | 0.4      |     000342 |
|  16 | Car    |           0 |          0 | -1.79141   | [496.96286 173.24014 538.26605 200.41988]     | [3.793096  1.5442586 1.651756 ] | [-5.5996456  1.5681386 43.118607 ]          |  -1.92016    | 0.4      |     000342 |
|  17 | Car    |           0 |          0 | -1.75531   | [498.56253 173.76149 538.6203  200.65036]     | [4.0435452 1.526797  1.6635847] | [-5.56714    1.5836931 43.296806 ]          |  -1.88281    | 0.485629 |     000342 |
|  18 | Car    |           0 |          0 |  1.62312   | [448.56326 187.53806 486.11194 221.20445]     | [3.8529978 1.5260634 1.6620697] | [-7.2034264  2.3097222 36.49721  ]          |   1.42908    | 0.4      |     000361 |
|  19 | Car    |           0 |          0 |  1.70763   | [459.26346 186.48265 525.5317  235.47852]     | [4.401576  1.4731457 1.68477  ] | [-4.043606   1.9897344 25.146986 ]          |   1.54915    | 0.994795 |     000361 |
|  20 | Car    |           0 |          0 |  2.0978    | [  9.631353 194.42357  292.00455  336.12112 ] | [4.0459166 1.6162028 1.7042167] | [-6.5800886  2.0016792 10.876166 ]          |   1.56402    | 0.991967 |     000361 |
|  21 | Car    |           0 |          0 |  1.87094   | [330.40808 193.72415 424.35898 249.78969]     | [3.846032  1.4238977 1.6050365] | [-6.9152317  2.1066473 21.687393 ]          |   1.56519    | 0.986001 |     000361 |
|  22 | Car    |           0 |          0 |  1.67533   | [503.52295 185.49284 543.4492  217.92065]     | [3.6108596 1.4580055 1.5921954] | [-4.2675223  2.1144137 35.67411  ]          |   1.55656    | 0.961102 |     000361 |
|  23 | Car    |           0 |          0 | -1.62814   | [629.20105 179.94244 660.1204  205.98886]     | [3.8934677 1.4570768 1.6242151] | [ 2.0069296  1.902214  43.38507  ]          |  -1.58276    | 0.914968 |     000361 |
|  24 | Car    |           0 |          0 | -0.0184923 | [704.8661  168.48557 793.77484 200.63863]     | [4.6440163 1.6928893 1.7736386] | [ 7.496447   1.4625871 39.253136 ]          |   0.168412   | 0.855945 |     000361 |
|  25 | Car    |           0 |          0 | -0.234602  | [711.81274 170.76266 806.65015 202.54648]     | [4.414915  1.5653192 1.701989 ] | [ 7.450685  1.462023 36.462814]             |  -0.0350589  | 0.778951 |     000361 |
|  26 | Car    |           0 |          0 |  1.57954   | [448.8942  187.43448 484.15085 220.95627]     | [4.03611   1.5149438 1.6595076] | [-7.2973857  2.2975228 36.60475  ]          |   1.3836     | 0.726657 |     000361 |
|  27 | Car    |           0 |          0 | -2.00961   | [ 767.14484  180.97588 1024.683    332.547  ] | [3.34438   1.4605255 1.571622 ] | [3.1825924 1.5799067 8.88607  ]             |  -1.67731    | 0.995562 |     000561 |
|  28 | Car    |           0 |          0 | -4.63532   | [554.3003  169.1669  588.3414  196.32036]     | [4.6288166 1.536352  1.7058711] | [-1.7471786  0.8386788 42.98396  ]          |  -4.68064    | 0.4      |     000645 |
|  29 | Car    |           0 |          0 | -1.527     | [587.7511  170.29799 611.94446 193.39958]     | [3.9006252 1.4837036 1.619451 ] | [-0.06919938  0.69603306 52.48728   ]       |  -1.53321    | 0.4      |     000645 |
|  30 | Car    |           0 |          0 | -0.462192  | [325.21725 175.6195  446.90063 222.57306]     | [3.5959294 1.4632854 1.5916889] | [-7.2267213  1.280471  24.197992 ]          |  -0.7546     | 0.994321 |     000645 |
|  31 | Car    |           0 |          0 | -1.45713   | [554.0917  170.17146 589.6776  196.09969]     | [4.298862  1.4685479 1.6662952] | [-1.7120973  0.8270486 42.88756  ]          |  -1.50173    | 0.90308  |     000645 |
|  32 | Car    |           0 |          0 | -1.53387   | [588.9503  170.50084 612.6925  193.0782 ]     | [3.8773324 1.447763  1.6142142] | [1.2353286e-03 6.7386359e-01 5.2503483e+01] |  -1.53875    | 0.844601 |     000645 |
|  33 | Car    |           0 |          0 | -1.51855   | [562.0158  168.62596 588.53326 194.04688]     | [3.534782  1.4826703 1.5791447] | [-1.6815149  0.6677291 47.251236 ]          |  -1.55882    | 0.4      |     000656 |
|  34 | Car    |           0 |          0 | -1.58648   | [563.266   168.21739 589.12305 194.07234]     | [3.6418655 1.510288  1.6221052] | [-1.6884133   0.66940445 47.342216  ]       |  -1.62683    | 0.745574 |     000656 |
|  35 | Car    |           0 |          0 | -1.31771   | [349.6594  181.06047 416.7373  219.59912]     | [3.8664184 1.4152125 1.5988343] | [-8.809963   1.2627827 28.365467 ]          |  -1.61649    | 0.4      |     000819 |
|  36 | Car    |           0 |          0 | -1.34503   | [349.38583 181.44804 413.80957 221.3836 ]     | [3.7233348 1.4648445 1.6160047] | [-8.853741   1.3268038 28.284908 ]          |  -1.64602    | 0.4      |     000819 |
|  37 | Car    |           0 |          0 | -0.769146  | [  0.      198.01648 122.64208 363.60742]     | [4.365714  1.4359276 1.6597145] | [-8.385055   1.6324794  8.803324 ]          |  -1.51514    | 0.4      |     000819 |
|  38 | Car    |           0 |          0 | -3.92731   | [  0.      196.21867 122.2487  355.7174 ]     | [4.0977416 1.4469345 1.6433935] | [-8.334945   1.6151462  8.894234 ]          |  -4.66535    | 0.4      |     000819 |
|  39 | Car    |           0 |          0 | -1.4875    | [458.0325  172.04436 487.3538  198.96074]     | [3.8032262 1.6624601 1.6909509] | [-9.366823   0.7838062 49.94068  ]          |  -1.67226    | 0.4      |     000819 |
|  40 | Car    |           0 |          0 | -1.36766   | [399.19662 181.09198 483.0808  235.52861]     | [3.9652812 1.4627497 1.6402134] | [-4.87007    1.3520998 21.314112 ]          |  -1.58991    | 0.994418 |     000819 |
|  41 | Car    |           0 |          0 | -1.19167   | [226.46902 188.23114 418.13794 298.05078]     | [3.4842556 1.4545707 1.5904306] | [-4.34215    1.5098323 11.377165 ]          |  -1.54874    | 0.994197 |     000819 |
|  42 | Car    |           0 |          0 | -1.41425   | [468.63715 179.43495 519.91846 216.27383]     | [3.6580071 1.4767603 1.6056623] | [-4.811882   1.2451848 30.647196 ]          |  -1.56902    | 0.989613 |     000819 |
|  43 | Car    |           0 |          0 | -1.57625   | [575.97687 175.86847 609.6192  208.01727]     | [3.7775774 1.5815908 1.6558608] | [-0.82372427  1.1219027  37.275867  ]       |  -1.5986     | 0.963454 |     000819 |
|  44 | Car    |           0 |          0 | -1.21909   | [229.55768 176.70142 346.5168  240.23668]     | [3.8953342 1.5655552 1.6625719] | [-8.649702   1.3559144 19.70512  ]          |  -1.62797    | 0.961342 |     000819 |
|  45 | Car    |           0 |          0 | -0.963847  | [  0.      166.73485 181.528   254.93544]     | [4.6275325 1.7798138 1.7984784] | [-12.272189    1.4070429  16.8334   ]       |  -1.58637    | 0.920533 |     000819 |
|  46 | Car    |           0 |          0 | -0.83671   | [  0.      198.03572 122.18141 361.28122]     | [4.3436165 1.4347506 1.6592621] | [-8.310734   1.6313088  8.836289 ]          |  -1.57647    | 0.827236 |     000819 |
|  47 | Car    |           0 |          0 | -1.28403   | [348.82755 181.8493  416.05493 221.23503]     | [3.48041   1.4472681 1.5857718] | [-8.787317   1.3237249 28.165665 ]          |  -1.58408    | 0.826579 |     000819 |
|  48 | Car    |           0 |          0 | -1.44319   | [457.84122 172.08116 489.47226 197.47932]     | [3.7436316 1.6953441 1.6953241] | [-9.290546   0.8187627 49.90028  ]          |  -1.62662    | 0.777654 |     000819 |
|  49 | Car    |           0 |          0 |  1.72443   | [437.8039  182.69557 505.5978  235.96059]     | [4.014972  1.6229662 1.6818159] | [-4.6992993  1.9882674 24.77036  ]          |   1.53823    | 0.986223 |     000839 |
|  50 | Car    |           0 |          0 | -4.41341   | [300.5898 183.3864 465.272  295.6075]         | [3.5137594 1.5357392 1.5974265] | [-3.6224818  1.7359407 11.970581 ]          |  -4.70202    | 0.992417 |     000871 |
|  51 | Car    |           0 |          0 | -1.57258   | [587.2833  179.17645 631.928   221.95415]     | [4.5314054 1.6393158 1.7526597] | [-0.07110755  1.9269626  30.591436  ]       |  -1.5756     | 0.963551 |     000871 |
|  52 | Car    |           0 |          0 | -4.58388   | [522.65686 183.63101 562.21765 213.63173]     | [3.7660851 1.4363    1.5963378] | [-3.5302315  2.029516  37.826603 ]          |  -4.67686    | 0.907724 |     000871 |
|  53 | Car    |           0 |          0 |  2.16573   | [ 21.947155 191.93898  195.8619   257.30957 ] | [4.543724  1.5019884 1.7064383] | [-13.789905    2.0955436  20.178642 ]       |   1.57215    | 0.99321  |     001352 |
|  54 | Car    |           0 |          0 | -4.45469   | [405.76633 182.2369  443.18317 207.23933]     | [4.1642632 1.590548  1.6886997] | [-13.77902     2.3155084  53.6839   ]       |  -4.70513    | 0.906861 |     001352 |
|  55 | Car    |           0 |          0 |  1.71253   | [479.47415 181.17035 523.7086  212.78665]     | [4.010057  1.4473808 1.6366053] | [-5.4023004  1.8863246 36.099266 ]          |   1.56455    | 0.4      |     001522 |
|  56 | Car    |           0 |          0 | -4.4035    | [348.61102 187.07541 451.72443 249.99913]     | [3.7966757 1.4816878 1.6181915] | [-5.6697373  1.9092376 19.783644 ]          |  -4.67971    | 0.99268  |     001522 |
|  57 | Car    |           0 |          0 | -4.47788   | [412.5616  185.28932 483.26923 231.77724]     | [3.6725965 1.4415953 1.5928011] | [-5.6214285  1.9077154 25.213787 ]          |  -4.69561    | 0.991548 |     001522 |
|  58 | Car    |           0 |          0 | -0.96371   | [  0.      192.55952 278.8652  374.     ]     | [3.9640212 1.659254  1.7018793] | [-5.849424   1.9510896  8.691481 ]          |  -1.54242    | 0.985425 |     001522 |
|  59 | Car    |           0 |          0 | -4.52987   | [448.86572 182.79146 503.7843  221.50328]     | [3.718603  1.465186  1.6020939] | [-5.554031   1.9053996 30.124483 ]          |  -4.71118    | 0.985269 |     001522 |
|  60 | Car    |           0 |          0 | -2.13156   | [ 896.9798   183.68901 1241.       374.     ] | [3.8795023 1.500819  1.6331761] | [3.0679786 1.5913975 4.074033 ]             |  -1.5212     | 0.946394 |     001522 |
|  61 | Car    |           0 |          0 | -4.54945   | [477.44626 180.2787  523.95465 212.46962]     | [4.1617885 1.4758967 1.6473135] | [-5.447715   1.8689942 36.13847  ]          |  -4.69849    | 0.910943 |     001522 |
|  62 | Car    |           0 |          0 | -0.591251  | [1092.1072  138.2055 1224.7297  176.5942]     | [4.2737904 1.5828959 1.7086173] | [23.213316    0.15392053 30.714636  ]       |   0.0515033  | 0.907746 |     001522 |
|  63 | Car    |           0 |          0 | -0.232766  | [779.7775  157.3583  881.8403  192.90314]     | [4.0102496 1.5157412 1.6569264] | [ 9.595248    0.85465693 31.712402  ]       |   0.0582684  | 0.876541 |     001522 |
|  64 | Car    |           0 |          0 | -4.54173   | [506.27246 180.13289 544.8303  206.4895 ]     | [4.137026  1.4738805 1.6365943] | [-5.0873613  1.9349539 43.624695 ]          |  -4.65759    | 0.843431 |     001522 |
|  65 | Car    |           0 |          0 | -1.67246   | [663.05164 173.47563 702.099   203.19928]     | [3.9749236 1.4734352 1.6263807] | [ 3.7136166  1.5074538 37.842316 ]          |  -1.57586    | 0.632919 |     001522 |
|  66 | Car    |           0 |          0 | -1.72186   | [726.0587  171.25183 765.77924 198.16504]     | [3.9240756 1.4384353 1.6049938] | [ 7.5465565  1.3525035 40.55032  ]          |  -1.53954    | 0.530051 |     001522 |
|  67 | Car    |           0 |          0 |  1.83585   | [  0.       0.     279.1313 369.    ]         | [4.9051166 1.8075237 1.8373969] | [-3.111476   1.4199591  3.9997568]          |   1.21425    | 0.430859 |     001558 |
|  68 | Car    |           0 |          0 |  2.07577   | [124.27046 191.8729  195.0558  221.1815 ]     | [4.106738  1.4884485 1.6619629] | [-25.804716   2.635862  41.450123]          |   1.52157    | 0.4      |     001735 |
|  69 | Car    |           0 |          0 |  2.08166   | [123.044846 191.41496  202.04477  222.08388 ] | [4.8043995 1.546871  1.749896 ] | [-25.810108    2.6838574  41.775604 ]       |   1.53083    | 0.4      |     001735 |
|  70 | Car    |           0 |          0 |  2.15289   | [ 32.86364 194.34213 130.18767 230.45175]     | [4.280993  1.4945416 1.6789293] | [-25.25759    2.590329  34.62909 ]          |   1.52618    | 0.905005 |     001735 |
|  71 | Car    |           0 |          0 |  2.06341   | [123.17086 192.20084 191.61885 221.1852 ]     | [3.9647586 1.4705521 1.63428  ] | [-25.878086   2.633407  41.349224]          |   1.50686    | 0.631903 |     001735 |
|  72 | Car    |           0 |          0 |  2.10855   | [110.62677 204.94011 233.5767  258.0416 ]     | [4.245867  1.4917608 1.6770499] | [-15.013858    2.6958086  24.959414 ]       |   1.57136    | 0.975519 |     001826 |
|  73 | Car    |           0 |          0 | -4.3123    | [292.9743  194.13284 352.0792  223.62816]     | [4.338842  1.5354943 1.7031447] | [-17.044004   2.865202  42.909874]          |  -4.68869    | 0.834829 |     001826 |
|  74 | Car    |           0 |          0 | -1.55995   | [565.1494  174.97119 613.8693  222.86104]     | [3.3494158 1.577888  1.6158075] | [-0.7589428  1.6577013 25.612728 ]          |  -1.58997    | 0.987574 |     001990 |
|  75 | Car    |           0 |          0 |  0.994805  | [ 979.7051   148.8984  1081.0035   190.35178] | [4.4002047 1.7069702 1.7341523] | [18.424484   0.7202249 31.957523 ]          |   1.51373    | 0.434655 |     001990 |
|  76 | Car    |           0 |          0 | -2.15002   | [1035.0768   184.01053 1153.3553   231.01181] | [3.5161548 1.4547496 1.6033254] | [16.368046  1.582548 23.918936]             |  -1.55459    | 0.4      |     002175 |
|  77 | Car    |           0 |          0 | -1.61285   | [602.7549  172.27596 637.6668  202.9575 ]     | [3.931366  1.5290387 1.6677488] | [ 0.73623747  1.1193458  37.218876  ]       |  -1.59153    | 0.4      |     002175 |
|  78 | Car    |           0 |          0 | -1.5306    | [602.7645  171.64789 637.33984 202.78352]     | [3.8710175 1.5520058 1.6619303] | [ 0.82213175  1.110917   37.228573  ]       |  -1.50699    | 0.4      |     002175 |
|  79 | Car    |           0 |          0 | -2.12751   | [ 958.0506   182.39694 1066.567    229.0179 ] | [3.4809554 1.4645047 1.5854697] | [13.734945   1.5342406 24.127544 ]          |  -1.61414    | 0.984027 |     002175 |
|  80 | Car    |           0 |          0 | -2.22983   | [1037.3331   184.4827  1155.017    230.94032] | [3.2528045 1.4321191 1.5642095] | [16.33592    1.5755819 23.753122 ]          |  -1.63213    | 0.928272 |     002175 |
|  81 | Car    |           0 |          0 | -1.61328   | [603.2186  173.06717 636.61707 202.45622]     | [3.4840665 1.4660616 1.597779 ] | [ 0.7239396  1.0954361 37.0296   ]          |  -1.59217    | 0.842214 |     002175 |
|  82 | Car    |           0 |          0 |  0.84943   | [1089.5311  188.6258 1223.      236.1871]     | [4.1461134 1.459017  1.6523327] | [19.122772  1.765622 24.536016]             |   1.50663    | 0.44306  |     002175 |
|  83 | Car    |           0 |          0 | -1.51891   | [575.6061  177.2812  631.7051  232.44553]     | [3.2336435 1.5765525 1.5888686] | [-0.18508707  1.7246442  22.53516   ]       |  -1.52786    | 0.994116 |     002231 |
|  84 | Car    |           0 |          0 |  1.56234   | [480.5073  182.80876 522.62756 223.13733]     | [3.8893657 1.561965  1.6796598] | [-4.720087   2.0178564 31.012459 ]          |   1.41196    | 0.4      |     002276 |
|  85 | Car    |           0 |          0 | -1.46409   | [444.42325 185.9511  502.80893 235.49461]     | [3.443092  1.4898816 1.5783218] | [-4.590368   1.9650369 24.415796 ]          |  -1.64863    | 0.995246 |     002276 |

## 2. Dataset

**velodyne_depth:**

Shape of the data = (N, 8)
- Consisting of Features: 
  - x
  - y
  - z
  - intensity
  - ...

In [1]:
import numpy as np
import pandas as pd
import open3d as o3d



# Load the .npy file
file_path = "/home/leo/workspace/Docker_tests/Torch1131CUDA117/VirConv/data/kitti/training/velodyne_depth/000004.npy"  # Update this with the correct path

data = np.load(file_path)

# Convert the numpy array to a pandas DataFrame for better visualization
df = pd.DataFrame(data)

# Display basic information
print(f"Shape of the data: {df.shape}")
# print(f"Data type: {df.dtypes}")
print("\n First few rows:"  )
display(df.head())

# Extract XYZ coordinates (assuming the first three columns represent X, Y, and Z)
points = data[:, :3]  # Adjust if necessary

# Create Open3D point cloud
point_cloud = o3d.geometry.PointCloud()
point_cloud.points = o3d.utility.Vector3dVector(points)

# Visualize the point cloud
o3d.visualization.draw_geometries([point_cloud])

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
Shape of the data: (99027, 8)

 First few rows:

          0          1         2    3    4    5    6    7
0  57.65625  21.000000  2.283203  0.0  0.0  0.0  0.0  2.0
1  57.59375  21.187500  2.283203  0.0  0.0  0.0  0.0  2.0
2  57.34375  21.703125  2.281250  0.0  0.0  0.0  0.0  2.0
3  57.06250  21.687500  2.273438  0.0  0.0  0.0  0.0  2.0
4  56.93750  21.859375  2.271484  0.0  0.0  0.0  0.0  2.0

[Open3D WARNING] GLFW Error: GLX: Failed to create context: GLXBadFBConfig
[Open3D WARNING] Failed to create window
[Open3D WARNING] [DrawGeometries] Failed creating OpenGL window.

libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast

**kitti_dbinfos_train_mm:**

Contains:
- name	
- path	
- image_idx	
- gt_idx	
- box3d_lidar	(7 values)
- num_points_in_gt	
- difficulty	
- bbox	
- score

In [21]:
import pickle
import pandas as pd

# Load the .pkl file
file_path = "/home/leo/workspace/Docker_tests/Torch1131CUDA117/VirConv/data/kitti/kitti_dbinfos_train_mm.pkl" 
with open(file_path, "rb") as f:
    data = pickle.load(f)

# Check if the data is a dictionary
if isinstance(data, dict):
    print("Keys in the dataset:", list(data.keys()))

    # Select a sample key and display its structure
    sample_key = list(data.keys())[0]
    sample_value = data[sample_key]

    if isinstance(sample_value, list) and len(sample_value) > 0:
        # Convert first few entries into a DataFrame for better visualization
        df = pd.DataFrame(sample_value) 
        pd.set_option("display.max_columns", None)  # Show all columns
        # pd.set_option("display.max_rows", 100)  # Adjust row display limit
        pd.set_option("display.max_colwidth", None)  # Show full content in columns

        display(df)  # Works in Jupyter Notebook
    else:
        print("Data under this key is not in list format.")
else:
    print("Data is not a dictionary.")

# Print Examples values for one image_index
print("Selected image index: ", sample_value[0]['image_idx'])
print(f"Lidar point cloud data path: {sample_value[0]['path']}")

# output the number of detected object for the first image_idx 
image_idx = sample_value[0]['image_idx']
num_objects = sum(1 for item in sample_value if item['image_idx'] == image_idx)
print("Number of objects in the image index: ", num_objects)

print("\nExample for the Box3D Lidar: \n")
print(sample_value[0]['box3d_lidar'])

Keys in the dataset: ['Car', 'Truck', 'Misc', 'Van', 'Pedestrian', 'Cyclist', 'Tram', 'Person_sitting']

,name,path,image_idx,gt_idx,box3d_lidar,num_points_in_gt,difficulty,bbox,score
0,Car,gt_database_mm/000004_Car_0.bin,000004,0,"[38.5496940612793, 15.734733581542969, -0.921228289604187, 4.01, 1.76, 1.49, -3.140796326794897]",79,1,"[280.38, 185.1, 344.9, 215.59]",-1.0
1,Car,gt_database_mm/000004_Car_1.bin,000004,1,"[51.459678649902344, 15.917068481445312, -0.909392774105072, 3.41, 1.8, 1.38, -3.1507963267948966]",26,-1,"[365.14, 184.54, 406.11, 205.2]",-1.0
2,Car,gt_database_mm/000017_Car_0.bin,000017,0,"[47.45068359375, -9.687284469604492, -0.6017827391624451, 4.35, 1.72, 1.62, 0.45920367320510325]",15,1,"[728.25, 173.97, 791.57, 200.2]",-1.0
3,Car,gt_database_mm/000026_Car_1.bin,000026,1,"[68.62593078613281, 4.244255065917969, -0.24827824532985687, 3.64, 1.59, 1.53, 0.15920367320510342]",12,-1,"[555.45, 174.38, 576.17, 191.19]",-1.0
4,Car,gt_database_mm/000029_Car_1.bin,000029,1,"[41.820045471191406, -3.437804937362671, -0.6345962882041931, 3.3, 1.69, 1.64, 0.059203673205103335]",62,1,"[652.31, 174.94, 690.16, 204.97]",-1.0
...,...,...,...,...,...,...,...,...,...
2097,Car,gt_database_mm/007480_Car_9.bin,007480,9,"[19.141502380371094, -5.700816631317139, -0.8005086183547974, 3.82, 1.69, 1.77, -1.5307963267948965]",127,2,"[749.78, 170.88, 917.51, 243.48]",-1.0
2098,Car,gt_database_mm/007480_Car_10.bin,007480,10,"[26.318410873413086, 7.139677047729492, -0.7598298788070679, 4.44, 1.59, 1.49, -4.690796326794897]",134,1,"[344.07, 180.05, 479.1, 224.15]",-1.0
2099,Car,gt_database_mm/007480_Car_11.bin,007480,11,"[29.068336486816406, 6.810037612915039, -0.739574670791626, 4.1, 1.63, 1.48, 1.5692036732051036]",49,2,"[382.7, 179.71, 495.48, 219.1]",-1.0
2100,Car,gt_database_mm/007480_Car_12.bin,007480,12,"[32.26978302001953, -1.8795024156570435, -0.7929317355155945, 4.08, 1.56, 1.41, 0.059203673205103335]",89,1,"[631.71, 179.85, 678.4, 214.37]",-1.0
2101,Car,gt_database_mm/007480_Car_13.bin,007480,13,"[47.30854797363281, -1.4479727745056152, -0.5912050604820251, 3.37, 1.58, 1.43, 0.019203673205103522]",11,-1,"[619.92, 176.9, 647.01, 199.92]",-1.0

Selected image index:  000004
Lidar point cloud data path: gt_database_mm/000004_Car_0.bin
Number of objects in the image index:  2

Example for the Box3D Lidar:

[38.54969406 15.73473358 -0.92122829  4.01        1.76        1.49
 -3.14079633]

**kitti_infos_test.pkl:**

In [24]:
import pickle
import pandas as pd

# Load the .pkl file
file_path = "/home/leo/workspace/Docker_tests/Torch1131CUDA117/VirConv/data/kitti/kitti_infos_test.pkl"  

with open(file_path, "rb") as f:
    data_test = pickle.load(f)

# Check if the data is a list
if isinstance(data_test, list) and len(data_test) > 0:
    print(f"Dataset contains {len(data_test)} entries.")
    
    # Extract the first few dictionaries and display as a DataFrame
    df_test = pd.DataFrame(data_test[:5])  # Convert first 5 entries into a DataFrame
    pd.set_option("display.max_columns", None)  # Show all columns
    pd.set_option("display.max_colwidth", None)  # Show full content in columns

    display(df_test)  # Works in Jupyter Notebook

    # Print keys of the first dictionary to understand structure
    print("Keys in each dictionary entry:", list(data_test[0].keys()))
else:
    print("Data format is unexpected:", type(data_test))

Dataset contains 160 entries.

,point_cloud,image,calib
0,"{'num_features': 4, 'lidar_idx': '000003'}","{'image_idx': '000003', 'image_shape': [375, 1242]}","{'P2': [[721.5377197265625, 0.0, 609.559326171875, 44.85728073120117], [0.0, 721.5377197265625, 172.85400390625, 0.2163791060447693], [0.0, 0.0, 1.0, 0.0027458840049803257], [0.0, 0.0, 0.0, 1.0]], 'R0_rect': [[0.9999239, 0.00983776, -0.007445048, 0.0], [-0.009869795, 0.9999421, -0.004278459, 0.0], [0.007402527, 0.004351614, 0.9999631, 0.0], [0.0, 0.0, 0.0, 1.0]], 'Tr_velo_to_cam': [[0.0075337449088692665, -0.9999713897705078, -0.00061660201754421, -0.004069766029715538], [0.01480249036103487, 0.0007280732970684767, -0.9998902082443237, -0.07631617784500122], [0.9998620748519897, 0.007523790001869202, 0.014807550236582756, -0.2717806100845337], [0.0, 0.0, 0.0, 1.0]]}"
1,"{'num_features': 4, 'lidar_idx': '000013'}","{'image_idx': '000013', 'image_shape': [375, 1242]}","{'P2': [[721.5377197265625, 0.0, 609.559326171875, 44.85728073120117], [0.0, 721.5377197265625, 172.85400390625, 0.2163791060447693], [0.0, 0.0, 1.0, 0.0027458840049803257], [0.0, 0.0, 0.0, 1.0]], 'R0_rect': [[0.9999239, 0.00983776, -0.007445048, 0.0], [-0.009869795, 0.9999421, -0.004278459, 0.0], [0.007402527, 0.004351614, 0.9999631, 0.0], [0.0, 0.0, 0.0, 1.0]], 'Tr_velo_to_cam': [[0.0075337449088692665, -0.9999713897705078, -0.00061660201754421, -0.004069766029715538], [0.01480249036103487, 0.0007280732970684767, -0.9998902082443237, -0.07631617784500122], [0.9998620748519897, 0.007523790001869202, 0.014807550236582756, -0.2717806100845337], [0.0, 0.0, 0.0, 1.0]]}"
2,"{'num_features': 4, 'lidar_idx': '000045'}","{'image_idx': '000045', 'image_shape': [375, 1242]}","{'P2': [[721.5377197265625, 0.0, 609.559326171875, 44.85728073120117], [0.0, 721.5377197265625, 172.85400390625, 0.2163791060447693], [0.0, 0.0, 1.0, 0.0027458840049803257], [0.0, 0.0, 0.0, 1.0]], 'R0_rect': [[0.9999239, 0.00983776, -0.007445048, 0.0], [-0.009869795, 0.9999421, -0.004278459, 0.0], [0.007402527, 0.004351614, 0.9999631, 0.0], [0.0, 0.0, 0.0, 1.0]], 'Tr_velo_to_cam': [[0.0075337449088692665, -0.9999713897705078, -0.00061660201754421, -0.004069766029715538], [0.01480249036103487, 0.0007280732970684767, -0.9998902082443237, -0.07631617784500122], [0.9998620748519897, 0.007523790001869202, 0.014807550236582756, -0.2717806100845337], [0.0, 0.0, 0.0, 1.0]]}"
3,"{'num_features': 4, 'lidar_idx': '000200'}","{'image_idx': '000200', 'image_shape': [375, 1242]}","{'P2': [[721.5377197265625, 0.0, 609.559326171875, 44.85728073120117], [0.0, 721.5377197265625, 172.85400390625, 0.2163791060447693], [0.0, 0.0, 1.0, 0.0027458840049803257], [0.0, 0.0, 0.0, 1.0]], 'R0_rect': [[0.9999239, 0.00983776, -0.007445048, 0.0], [-0.009869795, 0.9999421, -0.004278459, 0.0], [0.007402527, 0.004351614, 0.9999631, 0.0], [0.0, 0.0, 0.0, 1.0]], 'Tr_velo_to_cam': [[0.0075337449088692665, -0.9999713897705078, -0.00061660201754421, -0.004069766029715538], [0.01480249036103487, 0.0007280732970684767, -0.9998902082443237, -0.07631617784500122], [0.9998620748519897, 0.007523790001869202, 0.014807550236582756, -0.2717806100845337], [0.0, 0.0, 0.0, 1.0]]}"
4,"{'num_features': 4, 'lidar_idx': '000378'}","{'image_idx': '000378', 'image_shape': [375, 1242]}","{'P2': [[721.5377197265625, 0.0, 609.559326171875, 44.85728073120117], [0.0, 721.5377197265625, 172.85400390625, 0.2163791060447693], [0.0, 0.0, 1.0, 0.0027458840049803257], [0.0, 0.0, 0.0, 1.0]], 'R0_rect': [[0.9999239, 0.00983776, -0.007445048, 0.0], [-0.009869795, 0.9999421, -0.004278459, 0.0], [0.007402527, 0.004351614, 0.9999631, 0.0], [0.0, 0.0, 0.0, 1.0]], 'Tr_velo_to_cam': [[0.0075337449088692665, -0.9999713897705078, -0.00061660201754421, -0.004069766029715538], [0.01480249036103487, 0.0007280732970684767, -0.9998902082443237, -0.07631617784500122], [0.9998620748519897, 0.007523790001869202, 0.014807550236582756, -0.2717806100845337], [0.0, 0.0, 0.0, 1.0]]}"

Keys in each dictionary entry: ['point_cloud', 'image', 'calib']

**kitti_infos_train.pkl:**

In [23]:
import pickle
import pandas as pd

# Load the .pkl file
file_path = "/home/leo/workspace/Docker_tests/Torch1131CUDA117/VirConv/data/kitti/kitti_infos_train.pkl"  

with open(file_path, "rb") as f:
    data_test = pickle.load(f)

# Check if the data is a list
if isinstance(data_test, list) and len(data_test) > 0:
    print(f"Dataset contains {len(data_test)} entries.")
    
    # Extract the first few dictionaries and display as a DataFrame
    df_test = pd.DataFrame(data_test[:5])  # Convert first 5 entries into a DataFrame
    pd.set_option("display.max_columns", None)  # Show all columns
    pd.set_option("display.max_colwidth", None)  # Show full content in columns
    display(df_test)  # Works in Jupyter Notebook

    # Print keys of the first dictionary to understand structure
    print("Keys in each dictionary entry:", list(data_test[0].keys()))
else:
    print("Data format is unexpected:", type(data_test))

Dataset contains 560 entries.

,point_cloud,image,calib,annos
0,"{'num_features': 4, 'lidar_idx': '000004'}","{'image_idx': '000004', 'image_shape': [375, 1242]}","{'P2': [[721.5377197265625, 0.0, 609.559326171875, 44.85728073120117], [0.0, 721.5377197265625, 172.85400390625, 0.2163791060447693], [0.0, 0.0, 1.0, 0.0027458840049803257], [0.0, 0.0, 0.0, 1.0]], 'R0_rect': [[0.9999239, 0.00983776, -0.007445048, 0.0], [-0.009869795, 0.9999421, -0.004278459, 0.0], [0.007402527, 0.004351614, 0.9999631, 0.0], [0.0, 0.0, 0.0, 1.0]], 'Tr_velo_to_cam': [[0.0075337449088692665, -0.9999713897705078, -0.00061660201754421, -0.004069766029715538], [0.01480249036103487, 0.0007280732970684767, -0.9998902082443237, -0.07631617784500122], [0.9998620748519897, 0.007523790001869202, 0.014807550236582756, -0.2717806100845337], [0.0, 0.0, 0.0, 1.0]]}","{'name': ['Car', 'Car', 'DontCare', 'DontCare', 'DontCare', 'DontCare', 'DontCare'], 'truncated': [0.0, 0.0, -1.0, -1.0, -1.0, -1.0, -1.0], 'occluded': [0.0, 0.0, -1.0, -1.0, -1.0, -1.0, -1.0], 'alpha': [1.96, 1.88, -10.0, -10.0, -10.0, -10.0, -10.0], 'bbox': [[280.38, 185.1, 344.9, 215.59], [365.14, 184.54, 406.11, 205.2], [402.27, 166.69, 477.31, 197.98], [518.53, 177.31, 531.51, 187.17], [1207.5, 233.35, 1240.0, 333.39], [535.06, 177.65, 545.26, 185.82], [558.03, 177.88, 567.5, 184.65]], 'dimensions': [[4.01, 1.49, 1.76], [3.41, 1.38, 1.8], [-1.0, -1.0, -1.0], [-1.0, -1.0, -1.0], [-1.0, -1.0, -1.0], [-1.0, -1.0, -1.0], [-1.0, -1.0, -1.0]], 'location': [[-15.71, 2.16, 38.26], [-15.89, 2.23, 51.17], [-1000.0, -1000.0, -1000.0], [-1000.0, -1000.0, -1000.0], [-1000.0, -1000.0, -1000.0], [-1000.0, -1000.0, -1000.0], [-1000.0, -1000.0, -1000.0]], 'rotation_y': [1.57, 1.58, -10.0, -10.0, -10.0, -10.0, -10.0], 'score': [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0], 'difficulty': [1, -1, 1, -1, 0, -1, -1], 'index': [0, 1, -1, -1, -1, -1, -1], 'gt_boxes_lidar': [[38.5496940612793, 15.734733581542969, -0.921228289604187, 4.01, 1.76, 1.49, -3.140796326794897], [51.459678649902344, 15.917068481445312, -0.909392774105072, 3.41, 1.8, 1.38, -3.1507963267948966]], 'num_points_in_gt': [78, 26, -1, -1, -1, -1, -1]}"
1,"{'num_features': 4, 'lidar_idx': '000017'}","{'image_idx': '000017', 'image_shape': [375, 1242]}","{'P2': [[721.5377197265625, 0.0, 609.559326171875, 44.85728073120117], [0.0, 721.5377197265625, 172.85400390625, 0.2163791060447693], [0.0, 0.0, 1.0, 0.0027458840049803257], [0.0, 0.0, 0.0, 1.0]], 'R0_rect': [[0.9999239, 0.00983776, -0.007445048, 0.0], [-0.009869795, 0.9999421, -0.004278459, 0.0], [0.007402527, 0.004351614, 0.9999631, 0.0], [0.0, 0.0, 0.0, 1.0]], 'Tr_velo_to_cam': [[0.0075337449088692665, -0.9999713897705078, -0.00061660201754421, -0.004069766029715538], [0.01480249036103487, 0.0007280732970684767, -0.9998902082443237, -0.07631617784500122], [0.9998620748519897, 0.007523790001869202, 0.014807550236582756, -0.2717806100845337], [0.0, 0.0, 0.0, 1.0]]}","{'name': ['Car', 'DontCare'], 'truncated': [0.0, -1.0], 'occluded': [0.0, -1.0], 'alpha': [-2.23, -10.0], 'bbox': [[728.25, 173.97, 791.57, 200.2], [553.04, 167.02, 564.39, 175.9]], 'dimensions': [[4.35, 1.62, 1.72], [-1.0, -1.0, -1.0]], 'location': [[9.71, 1.73, 47.16], [-1000.0, -1000.0, -1000.0]], 'rotation_y': [-2.03, -10.0], 'score': [-1.0, -1.0], 'difficulty': [1, -1], 'index': [0, -1], 'gt_boxes_lidar': [[47.45068359375, -9.687284469604492, -0.6017827391624451, 4.35, 1.72, 1.62, 0.45920367320510325]], 'num_points_in_gt': [12, -1]}"
2,"{'num_features': 4, 'lidar_idx': '000026'}","{'image_idx': '000026', 'image_shape': [375, 1242]}","{'P2': [[721.5377197265625, 0.0, 609.559326171875, 44.85728073120117], [0.0, 721.5377197265625, 172.85400390625, 0.2163791060447693], [0.0, 0.0, 1.0, 0.0027458840049803257], [0.0, 0.0, 0.0, 1.0]], 'R0_rect': [[0.9999239, 0.00983776, -0.007445048, 0.0], [-0.009869795, 0.9999421, -0.004278459, 0.0], [0.007402527, 0.004351614, 0.9999631, 0.0], [0.0, 0.0, 0.0, 1.0]], 'Tr_velo_to_cam': [[0.0075337449088692665, -0.9999713897705078, -0.00061660201754421, -0.004069766029715538], [0.01480249036103487, 0.0007280732970684767, -0.9998902082443237, -0.07631617784500122], [0.9998620748519897, 0.007523790001869202, 0.014807550236582756, -0.2717806100845337], [0.0, 0.0, 0.0, 1.0]]}","{'name': ['Truck', 'Car'], 'truncated': [0.0, 0.0], 'occluded': [1.0, 0.0], 'alpha': [1.8, -1.67], 'bbox': [[633.9, 155.08, 704.57, 211.64], [555.45, 174.38, 576.17, 191.19]], 'dimensions': [[6.19, 2.66, 2.23], [3.64, 1.53, 1.59]], 'location': [[3.16, 1.86, 37.22], [-4.22, 1.7, 68.34]], 'rotation_y': [1.89, -1.73], 'score': [-1.0, -1.0], 'difficulty': [1, -1], 'index': [0, 1], 'gt_boxes_lidar': [[37.51104736328125, -3.137512683868408, -0.2464635819196701, 6.19, 2.23, 2.66, -3.4607963267948962], [68.62593078613281, 4.244255065917969, -0.24827824532985687, 3.64, 1.59, 1.53, 0.15920367320510342]], 'num_points_in_gt': [255, 12]}"
3,"{'num_features': 4, 'lidar_idx': '000029'}","{'image_idx': '000029', 'image_shape': [375, 1242]}","{'P2': [[721.5377197265625, 0.0, 609.559326171875, 44.85728073120117], [0.0, 721.5377197265625, 172.85400390625, 0.2163791060447693], [0.0, 0.0, 1.0, 0.0027458840049803257], [0.0, 0.0, 0.0, 1.0]], 'R0_rect': [[0.9999239, 0.00983776, -0.007445048, 0.0], [-0.009869795, 0.9999421, -0.004278459, 0.0], [0.007402527, 0.004351614, 0.9999631, 0.0], [0.0, 0.0, 0.0, 1.0]], 'Tr_velo_to_cam': [[0.0075337449088692665, -0.9999713897705078, -0.00061660201754421, -0.004069766029715538], [0.01480249036103487, 0.0007280732970684767, -0.9998902082443237, -0.07631617784500122], [0.9998620748519897, 0.007523790001869202, 0.014807550236582756, -0.2717806100845337], [0.0, 0.0, 0.0, 1.0]]}","{'name': ['Misc', 'Car', 'DontCare', 'DontCare'], 'truncated': [0.0, 0.0, -1.0, -1.0], 'occluded': [0.0, 0.0, -1.0, -1.0], 'alpha': [1.8, -1.71, -10.0, -10.0], 'bbox': [[490.15, 174.98, 542.09, 227.7], [652.31, 174.94, 690.16, 204.97], [590.54, 172.05, 602.07, 183.37], [576.03, 172.59, 588.41, 188.39]], 'dimensions': [[2.07, 1.61, 1.21], [3.3, 1.64, 1.69], [-1.0, -1.0, -1.0], [-1.0, -1.0, -1.0]], 'location': [[-3.03, 1.7, 23.25], [3.46, 1.78, 41.53], [-1000.0, -1000.0, -1000.0], [-1000.0, -1000.0, -1000.0]], 'rotation_y': [1.67, -1.63, -10.0, -10.0], 'score': [-1.0, -1.0, -1.0, -1.0], 'difficulty': [0, 1, -1, -1], 'index': [0, 1, -1, -1], 'gt_boxes_lidar': [[23.538684844970703, 3.0487143993377686, -0.6920979619026184, 2.07, 1.21, 1.61, -3.2407963267948965], [41.820045471191406, -3.437804937362671, -0.6345962882041931, 3.3, 1.69, 1.64, 0.059203673205103335]], 'num_points_in_gt': [205, 61, -1, -1]}"
4,"{'num_features': 4, 'lidar_idx': '000053'}","{'image_idx': '000053', 'image_shape': [375, 1242]}","{'P2': [[721.5377197265625, 0.0, 609.559326171875, 44.85728073120117], [0.0, 721.5377197265625, 172.85400390625, 0.2163791060447693], [0.0, 0.0, 1.0, 0.0027458840049803257], [0.0, 0.0, 0.0, 1.0]], 'R0_rect': [[0.9999239, 0.00983776, -0.007445048, 0.0], [-0.009869795, 0.9999421, -0.004278459, 0.0], [0.007402527, 0.004351614, 0.9999631, 0.0], [0.0, 0.0, 0.0, 1.0]], 'Tr_velo_to_cam': [[0.0075337449088692665, -0.9999713897705078, -0.00061660201754421, -0.004069766029715538], [0.01480249036103487, 0.0007280732970684767, -0.9998902082443237, -0.07631617784500122], [0.9998620748519897, 0.007523790001869202, 0.014807550236582756, -0.2717806100845337], [0.0, 0.0, 0.0, 1.0]]}","{'name': ['Van', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'DontCare', 'DontCare'], 'truncated': [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, -1.0], 'occluded': [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 2.0, -1.0, -1.0], 'alpha': [-2.32, 1.86, -1.79, 1.7, 1.64, 1.46, 1.64, -10.0, -10.0], 'bbox': [[865.23, 0.0, 1241.0, 374.0], [173.62, 180.91, 429.48, 359.85], [707.54, 185.88, 834.49, 271.76], [444.83, 180.67, 519.74, 231.01], [499.17, 171.42, 546.19, 212.24], [653.39, 176.6, 706.53, 216.76], [526.94, 173.21, 563.54, 203.04], [629.35, 176.06, 655.43, 199.02], [552.27, 177.1, 575.23, 195.89]], 'dimensions': [[5.62, 2.38, 1.98], [3.85, 1.52, 1.5], [3.68, 1.43, 1.59], [4.12, 1.29, 1.59], [3.59, 1.52, 1.61], [4.28, 1.51, 1.65], [3.95, 1.48, 1.64], [-1.0, -1.0, -1.0], [-1.0, -1.0, -1.0]], 'location': [[3.03, 1.7, 2.98], [-3.19, 1.62, 8.15], [2.97, 1.7, 14.21], [-3.63, 1.53, 20.88], [-3.48, 1.49, 28.91], [2.76, 1.68, 29.57], [-3.4, 1.52, 38.08], [-1000.0, -1000.0, -1000.0], [-1000.0, -1000.0, -1000.0]], 'rotation_y': [-1.58, 1.49, -1.59, 1.53, 1.52, 1.55, 1.55, -10.0, -10.0], 'score': [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0], 'difficulty': [-1, 0, 0, 0, 1, 0, 2, -1, -1], 'index': [0, 1, 2, 3, 4, 5, 6, -1, -1], 'gt_boxes_lidar': [[3.2712159156799316, -3.0134685039520264, -0.5829606652259827, 5.62, 1.98, 2.38, 0.009203673205103513], [8.438636779785156, 3.205982208251953, -0.813231348991394, 3.85, 1.5, 1.52, -3.0607963267948968], [14.500588417053223, -2.952075242996216, -0.9399587512016296, 3.68, 1.59, 1.43, 0.019203673205103522], [21.16689682006836, 3.646590232849121, -0.7005481719970703, 4.12, 1.59, 1.29, -3.100796326794897], [29.196075439453125, 3.4971745014190674, -0.46321332454681396, 3.59, 1.61, 1.52, -3.0907963267948966], [29.85948944091797, -2.7403879165649414, -0.7172104120254517, 4.28, 1.65, 1.51, -3.1207963267948964], [38.365909576416016, 3.4186363220214844, -0.4182164669036865, 3.95, 1.64, 1.48, -3.1207963267948964]], 'num_points_in_gt': [3737, 873, 528, 135, 72, 51, 17, -1, -1]}"

Keys in each dictionary entry: ['point_cloud', 'image', 'calib', 'annos']